volumes:
    duc_database:
    duc_config:

services:
  duc-service:
    build: .
    ports:
      # example 80 -> 80
      - target: 80
        published: 80
        protocol: tcp
        mode: host
    volumes:
      # example: scan the whole root partition
      - type: bind
        source: /
        target: /scan/root
        read_only: true
      # persist configuration
      - type: volume
        source: config
        target: /config
      # Persist databases outside the container
      - type: volume
        source: snapshots
        target: /snapshots
